### ISSUE TITLE
Can't build FlaUInspect

### ISSUE THREAD

**Issue by embronne** [FlauTech/FlaUInspect#7]
Hi,

Sorry if I'm missing something obvious, but I can't build FlaUInspect.

The errors are:

Severity|Code|Description|Project|File|Line|Suppression State
----|----|----|----|----|----|----
Error|CS1003|Syntax error, ',' expected|FlaUInspect|E:\projects\Misc\FlaUInspect\src\FlaUInspect\ViewModels\ElementViewModel.cs|77|Active
Error|CS0206|A property or indexer may not be passed as an out or ref parameter|FlaUInspect|E:\projects\Misc\FlaUInspect\src\FlaUInspect\ViewModels\ElementViewModel.cs|77|Active
Error|CS0103|The name 'value' does not exist in the current context|FlaUInspect|E:\projects\Misc\FlaUInspect\src\FlaUInspect\ViewModels\ElementViewModel.cs|77|Active
Error|CS0103|The name 'value' does not exist in the current context|FlaUInspect|E:\projects\Misc\FlaUInspect\src\FlaUInspect\ViewModels\ElementViewModel.cs|77|Active

The offending line of code is:

    public ControlType ControlType => AutomationElement.Properties.ControlType.TryGetValue(out ControlType value) ? value : ControlType.Custom;

Specifically, it's about `out ControlType value`.

I haven't been  programming in C# for some time, so I'm not up-to-date with the syntax, and am only superficially familiar with the `=>`-notation. So again, sorry if I'm missing something obvious.

Can you help?

Thanks, regards, Miel.

**Comment by MossFrog** [comment]
I seem to have the same issue, did you find a solution?

**Comment by Roemer** [comment]
Are you using Visual Studio 2017?

**Comment by embronne** [comment]
No, 2015.

**Comment by Roemer** [comment]
You need VS 2017 to build it.

**Comment by embronne** [comment]
OK, that works.
